config/routes.rb
Interpret::Engine.routes.draw do
  scope ":locale" do
    resources :translations, :only => [:destroy, :edit, :update, :create] do
      collection do
        get :live_edit
      end
    end

    resources :tools, :only => :index do
      collection do
        get :export
        post :import
        post :dump
        post :run_update
      end
    end

    match "search", :to => "search#index"
    resources :missing_translations
    match "blank", :to => "missing_translations#blank", :as => "blank_translations"
    match "unused", :to => "missing_translations#unused", :as => "unused_translations"
    match "stale", :to => "missing_translations#stale", :as => "stale_translations"

    root :to => "translations#index"
  end

  match "/", :to => "translations#welcome"
end

app/models/interpret/ability.rb
module Interpret
  class Ability
    include CanCan::Ability

    def initialize(user)
      can :manage, :all
    end
  end
end

app/models/interpret/expiration_observer.rb
module Interpret

  class ExpirationObserver < ActiveRecord::Observer
    observe Interpret::Translation

    def after_update(record)
      run_expiration(record) if record.value_changed?
    end

    def after_create(record)
      run_expiration(record)
    end

    def after_destroy(record)
      run_expiration(record)
    end

  protected
    # expiration logic for your app
    def expire_cache(key)
    end

    def expire_cache_all
    end

  private
    def run_expiration(record)
      Interpret.backend.reload! if Interpret.backend
      expire_cache(record.key)
    end
  end
end

app/controllers/interpret/base_controller.rb
class Interpret::BaseController < Interpret.parent_controller.classify.constantize
  before_filter :set_locale
  before_filter { authorize! :use, :interpret }
  before_filter :check_authorized_language
  layout 'interpret/interpret'
  helper Interpret::InterpretHelper

protected
  def current_interpret_user
    send(Interpret.current_user)
  end

  def current_ability
    @current_ability ||= Interpret.ability.new(current_interpret_user)
  end

  def default_url_options(options = {})
    options.merge({:locale => I18n.locale})
  end


private
  def set_locale
    I18n.locale = params[:locale] if params[:locale]
  end

  def check_authorized_language
    authorize! :use, :"interpret_in_#{I18n.locale}"
  end
end

app/controllers/interpret/missing_translations_controller.rb
class Interpret::MissingTranslationsController < Interpret::BaseController
  def index
    authorize! :read, :missing_translations
    return if I18n.locale == I18n.default_locale

    case ActiveRecord::Base.connection.adapter_name
    when "Mysql2"
      res = ActiveRecord::Base.connection.execute("select t.id from translations t where t.locale ='#{I18n.default_locale}' and (select count(*) from translations t2 where t2.key = t.key and t2.locale ='#{I18n.locale}') = 0")

    when "SQLite"
      res = ActiveRecord::Base.connection.execute("select t.id from translations t where t.locale ='#{I18n.default_locale}' and (select count(*) from translations t2 where t2.key = t.key and t2.locale ='#{I18n.locale}') = 0")

    else
      raise NotImplementedError, "database adapter not supported"
    end

    ids = res.map{|x| x.first}
    translations = Interpret::Translation.allowed.where(:id => ids).order("translations.key ASC").all
    translations = translations.select{|x| x.value.present?}
    @missing_translations = translations.map{|x| {:ref_value => x.value, :key => x.key, :source => x}}
  end

  def blank
    authorize! :read, :blank_translations
    @blank_translations = Interpret::Translation.allowed.locale(I18n.locale).where(:value => "--- \"\"\n")
    @ref_translations = Interpret::Translation.allowed.locale(I18n.default_locale).where(:key => @blank_translations.map{|x| x.key})

    @blank_translations.map do |x|
      foo = @ref_translations.detect{|y| x.key == y.key}
      [x, foo ? foo.value : nil]
    end
  end

  def unused
    authorize! :read, :unused_translations
    used_keys = Interpret::Translation.allowed.locale(I18n.default_locale).all.map{|x| x.key}
    @unused_translations = Interpret::Translation.allowed.locale(I18n.locale).where("translations.key NOT IN (?)", used_keys)
  end

  def stale
    authorize! :read, :stale_translations
    @stale_translations = Interpret::Translation.allowed.stale.locale(I18n.locale).order("translations.key ASC")
    refs = Interpret::Translation.locale(I18n.default_locale).where(:key => @stale_translations.map{|x| x.key})
    @stale_translations.map!{|x| [x, refs.detect{|y| y.key == x.key}]}
  end
end

app/controllers/interpret/search_controller.rb
class Interpret::SearchController < Interpret::BaseController
  before_filter { authorize! :use, :search }

  def index
    if request.post?
      opts = {}
      opts[:key] = params[:key] if params[:key].present?
      opts[:value] = params[:value] if params[:value].present?
      redirect_to search_url(opts)
    else
      if params[:key].present? || params[:value].present?
        sanitizer = case ActiveRecord::Base.connection.adapter_name
                    when "SQLite"
                      if Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new("1.9")
                        lambda {|x| "%#{x}%"}
                      else
                        lambda {|x| "%#{CGI.escape(x)}%"}
                      end
                    else
                      lambda {|x| "%#{CGI.escape(x)}%"}
                    end
        t = Interpret::Translation.arel_table
        search_key = params[:key].present? ? params[:key].split(" ").map{|x| sanitizer.call(x)} : []
        search_value = params[:value].present? ? params[:value].split(" ").map{|x| sanitizer.call(x)} : []
        if search_value.any? && search_key.any?
          @translations = Interpret::Translation.allowed.locale(I18n.locale).where(t[:key].matches_all(search_key).or(t[:value].matches_all(search_value))).order("translations.key ASC")
        elsif search_key.any?
          @translations = Interpret::Translation.allowed.locale(I18n.locale).where(t[:key].matches_all(search_key)).order("translations.key ASC")
        else
          @translations = Interpret::Translation.allowed.locale(I18n.locale).where(t[:value].matches_all(search_value)).order("translations.key ASC")
        end
      end
    end
  end
end

app/controllers/interpret/tools_controller.rb
class Interpret::ToolsController < Interpret::BaseController
  before_filter { authorize! :use, :tools }

  def dump
    Interpret::Translation.dump

    session.delete(:tree)
    Interpret.backend.reload! if Interpret.backend
    redirect_to tools_url, :notice => "Dump done."
  end

  def export
    require 'ya2yaml'

    translations = Interpret::Translation.locale(I18n.locale).all
    hash = Interpret::Translation.export(translations)
    text = hash.ya2yaml

    send_data text[5..text.length], :filename => "#{I18n.locale}.yml", :type => "text/plain", :disposition => "attachment"
  end

  def run_update
    Interpret::Translation.update
    Interpret.backend.reload! if Interpret.backend
    redirect_to tools_url, :notice => "Update done"
  end

  def import
    unless params.has_key? :file
      redirect_to tools_url, :alert => "You have to select a file to import."
      return
    end

    begin
      Interpret::Translation.import(params[:file])
    rescue Exception => e
      redirect_to tools_url, :alert => "Error when importing: #{e.message}"
      return
    end

    session.delete(:tree)
    Interpret.backend.reload! if Interpret.backend

    redirect_to tools_url, :notice => "Import successfully done."
  end
end

app/controllers/interpret/translations_controller.rb
module Interpret
  class TranslationsController < Interpret::BaseController
    before_filter :get_tree, :only => :index
    authorize_resource :class => "Interpret::Translation"

    def welcome
      redirect_to root_url
    end

    def index
      key = params[:key]
      t = Interpret::Translation.arel_table
      if key
        @translations = Interpret::Translation.allowed.locale(I18n.locale).where(t[:key].matches("#{CGI.escape(key)}.%")).order("translations.key ASC")
        if I18n.locale != I18n.default_locale
          @references = Interpret::Translation.allowed.locale(I18n.default_locale).where(t[:key].matches("#{CGI.escape(key)}.%")).order("translations.key ASC")
        end
      else
        @translations = Interpret::Translation.allowed.locale(I18n.locale).where(t[:key].does_not_match("%.%")).order("translations.key ASC")
        if I18n.locale != I18n.default_locale
          @references = Interpret::Translation.allowed.locale(I18n.default_locale).where(t[:key].does_not_match("%.%")).order("translations.key ASC")
        end
      end

      # not show translations inside nested folders, \w avoids dots
      @translations = @translations.select{|x| x.key =~ /#{key}\.\w+$/} if key
      @references = @references.select{|x| x.key =~ /#{key}\.\w+$/} if key && @references

      @total_keys_number = Interpret::Translation.locale(I18n.locale).count
    end

    def edit
      @translation = Interpret::Translation.find(params[:id])
    end

    def update
      @translation = Interpret::Translation.find(params[:id])
      old_value = @translation.value

      respond_to do |format|
        if @translation.update_attributes(params[:translation].presence || params[:interpret_translation])
          msg = ""
          msg << "By [#{current_interpret_user}]. " if current_interpret_user
          msg << "Locale: [#{@translation.locale}], key: [#{@translation.key}]. The translation has been changed from [#{old_value}] to [#{@translation.value}]"
          Interpret.logger.info msg

          format.html { redirect_to :back }
          format.xml  { head :ok }
          format.json { head :ok }
        else
          Interpret.logger.error "ERROR ON UPDATE: #{@translation.errors.inspect}"
          format.html { redirect_to :back }
          format.xml  { render :xml => @translation.errors, :status => :unprocessable_entity }
          format.json { render :status => :unprocessable_entity }
        end
      end
    end

    def create
      @translation = Interpret::Translation.new params[:translation]

      if @translation.save
        flash[:notice] = "New translation created for #{@translation.key}"
        redirect_to :back
      else
        flash[:alert] = "Error when creating a new translation"
        redirect_to :back
      end
    end

    def destroy
      @translation = Interpret::Translation.find(params[:id])

      @translation.destroy
      flash[:notice] = "Translation #{@translation.key} destroyed."
      redirect_to :back
    end

  private
    def get_tree
      @tree ||= Interpret::Translation.get_tree
    end
  end
end

app/helpers/interpret/interpret_helper.rb
module Interpret
  module InterpretHelper
    # Generates the html tree from the given keys
    def interpret_show_tree(tree, origin_keys)
      tree = tree.first[1]
      unless origin_keys.nil?
        origin_keys.split(".").each do |key|
          tree = tree[key]
        end
      end
      build_tree(tree, origin_keys)
    end

    def interpret_title(title)
      content_for :title do
        title
      end
    end

  private

    def build_tree(hash, origin_keys = "", prev_key = "")
      out = "<ul>"
      if origin_keys.present? && prev_key.blank?
        parent_key = origin_keys.split(".")[0..-2].join(".")
        if parent_key.blank?
          out << "<li>#{link_to "..", root_path}</li>"
        else
          out << "<li>#{link_to "..", root_path(:key => parent_key)}</li>"
        end
      end
      hash.keys.each do |key|
        out << "<li>"
        out << "#{link_to key, root_path(:key => "#{origin_keys.blank? ? "" : "#{origin_keys}."}#{prev_key}#{key}")}"
        out << "</li>"
      end
      out << "</ul>"
      out.html_safe
    end
  end
end

app/views/interpret/missing_translations/blank.html.erb
<% if @blank_translations.empty? %>
  <p>There are no blank translations</p>
<% else %>
  <p>There are <%= @blank_translations.size %> blank translations in this
  language [ <%= I18n.locale %> ]. These are translations that exists but are
  empty strings, so I show you them in case you want to take some action.</p>
  <table>
    <thead>
      <tr class="header">
        <th>Key</th>
        <th>Value in [ <%= I18n.default_locale %> ]</th>
        <th>Your translation to [ <%= I18n.locale %> ]</th>
        <th>Delete</th>
      </tr>
    </thead>
    <% @blank_translations.each do |trans, ref| %>
      <tr>
        <td><%= trans.key %></td>
        <td><%= ref || "It's empty" %></td>
        <td>
          <%= form_for Interpret::Translation.new, :url => translations_path do |f| %>
            <%= f.hidden_field "locale", :value => I18n.locale %>
            <%= f.hidden_field "key", :value => trans.key %>
            <%= f.text_area :value, :rows => 4, :cols => 60 %>
            <%= submit_tag "Create" %>
          <% end %>
        </td>
        <td>
          <%= link_to "Destroy it", trans, :method => :delete, :confirm => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/interpret/missing_translations/index.html.erb
<% if I18n.locale == I18n.default_locale %>
  <p>There can't be missing translations for the main language</p>
<% elsif @missing_translations.empty? %>
  <p>There are no missing translations</p>
<% else %>
  <p>There are <%= @missing_translations.size %> missing translations in [<%= I18n.locale %>]. You can
  create them below and you can see the translation key and also the original
  content in the reference language [ <%= I18n.default_locale %> ]
  </p>
  <table id='missing_translations'>
    <thead>
      <tr class="header">
        <th>Key</th>
        <th>Value in [ <%= I18n.default_locale %> ]</th>
        <th>Your translation to [ <%= I18n.locale %> ]</th>
        <% if can? :destroy, Interpret::Translation %>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @missing_translations.each do |trans| %>
        <tr>
          <td><%= trans[:key] %></td>
          <td><%= trans[:ref_value] %></td>
          <td>
            <%= form_for Interpret::Translation.new, :url => translations_path do |f| %>
              <%= f.hidden_field "locale", :value => I18n.locale %>
              <%= f.hidden_field "key", :value => trans[:key] %>
              <%= f.text_area :value, :rows => 4, :cols => 60 %>
              <%= submit_tag "Create" %>
            <% end %>
          </td>
          <% if can? :destroy, trans[:source] %>
            <td>
              <%= link_to "Destroy", trans[:source], :method => :delete, :confirm => "Are you sure?" %>
              the original [ <%= I18n.default_locale %> ] translation.
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/interpret/missing_translations/stale.html.erb
<% if I18n.locale == I18n.default_locale %>
  <p>There can't be stale translations for the main language</p>

<% elsif @stale_translations.empty? %>
  <p>There are no stale translations</p>

<% else %>
  <p>There are <%= @stale_translations.size %> stale translations in [<%= I18n.locale %>].</p>
  <p>
    They have been modified in the master language (<%= I18n.default_locale %>)
    so probably you want to change them in the current languge too.
    Once you think your new adaptation is correct click on "Mark as OK" button and that translation will no longer appear as stale.
  </p>
  <table id='stale_translations'>
    <thead>
      <tr class="header">
        <th>Key</th>
        <th>Value in [ <%= I18n.default_locale %> ]</th>
        <th>Your translation to [ <%= I18n.locale %> ]</th>
        <th>Actions</th>
      </tr>
    </thead>
    <% @stale_translations.each do |trans, ref| %>
      <tr>
        <td class='key'><%= trans.key %></td>
        <td><%= ref.value %></td>
        <td class='content' id='translation_<%= trans.id %>'>
            <%= best_in_place trans, :value,
                :type => :textarea,
                :path => translation_path(trans),
                :activator => "#translation_#{trans.id}",
                :sanitize => false %>
        </td>
        <td>
          <%= form_for trans, :url => translation_path(trans) do |f| %>
            <%= f.hidden_field :stale, :value => false %>
            <%= submit_tag "Mark as OK" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/interpret/missing_translations/unused.html.erb
<% unless @unused_translations %>
  <p>There are no useless translations</p>
<% else %>
  <p>There are <%= @unused_translations.size %> translations that exists for
  the [ <%= I18n.locale %> ] language, but DO NOT exists for [ <%= I18n.default_locale %> ].
  You probably want to do something about it.
  </p>

  <table>
    <thead>
      <tr class="header">
        <th>Key</th>
        <th>Value in [ <%= I18n.locale %> ]</th>
        <th>Delete</th>
      </tr>
    </thead>
    <% @unused_translations.each do |trans| %>
      <tr>
        <td><%= trans.key %></td>
        <td><%= trans.value %></td>
        <td>
          <%= link_to "Destroy it", trans, :method => :delete, :confirm => "Are you sure?" %>
        </td>
      </tr>
    <% end%>
  </table>
<% end %>