test_app/config/routes.rb
InterpretApp::Application.routes.draw do
  root :to => redirect("/es")

  mount Interpret::Engine => "/interpret"

  scope ":locale" do
    get "archives", :to => "pages#archives"
    get "links", :to => "pages#links"
    get "resources", :to => "pages#resources"
    get "contact", :to => "pages#contact"

    post "toggle_edition_mode", :to => "application#toggle_edition_mode"

    namespace :admin do
      get 'dashboard', :to => "dashboard#index"
    end

    root :to => "pages#index"
  end
end

test_app/app/models/interpret_ability.rb
class InterpretAbility
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

test_app/app/models/my_sweeper.rb
class MySweeper < Interpret::ExpirationObserver
  def expire_cache
    puts "Custom app expiration logic"
  end
end

test_app/app/models/user.rb
class User < ActiveRecord::Base
end

test_app/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'backoffice'

  def index
  end
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_current_user
  helper_method :current_user
  before_filter :set_locale

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : User.first
  end

  def set_current_user
    session[:user_id] = User.first
  end

  def toggle_edition_mode
    Interpret.live_edit = !Interpret.live_edit

    redirect_to :back
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    options.merge({:locale => I18n.locale})
  end

end

test_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/views/admin/dashboard/index.html.erb
Another Backoffice section

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interpret Demo</title>
  <%= stylesheet_link_tag "default" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="demo_sidebar">
    <p>
    This is a DEMO site to provide an example usage of <a href="https://github.com/rogercampos/interpret">Interpret</a>.
    </p>

    <p>
      <ul>
        <li>
          <%= link_to "Login to interpret", interpret.root_path %>
        </li>
      </ul>
    </p>
    <br/>

    <p>
    <% if current_user %>
      You are currently logged in
    <% else %>
      You are not logged in
    <% end %>
    </p>

    <br/>
    <p>
      Thanks to <a href="http://nodethirtythree.com">NodeThirtyThree</a> to provide this template in order to demostrate a real website.
    </p>
  </div>

  <div id="outer">

    <div id="upbg"></div>

    <div id="inner">

      <div id="header">
        <h1><%= t "main_header_html" %></h1>
        <h2><%= t "main_h2" %></h2>
      </div>

      <div id="splash"></div>

      <div id="menu">
        <ul>
          <li class="first"><a href="/">Home</a></li>
          <li><%= link_to "Archives", archives_path %></li>
          <li><%= link_to "Links", links_path %></li>
          <li><%= link_to "Resources", resources_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>

        <div id="lang_menu">
          Language:
          <%= link_to "English", :locale => :en %>
          |
          <%= link_to "Spanish", :locale => :es %>
        </div>
      </div>


      <div id="primarycontent">
        <%= yield %>
      </div>

      <div id="secondarycontent">

        <!-- secondary content start -->

        <h3><%= t "about_me" %></h3>
        <div class="content">
          <%= image_tag "pic2.jpg", :class => "picB" %>
          <p><%= t "about_me_text_html" %></p>
        </div>

        <h3><%= t "topics" %></h3>
        <div class="content">
          <ul class="linklist">
            <li class="first"><%= t "t1_html", :scope => "topics_list" %></li>
            <li><%= t "t2_html", :scope => "topics_list" %></li>
            <li><%= t "t3_html", :scope => "topics_list" %></li>
            <li><%= t "t4_html", :scope => "topics_list" %></li>
            <li><%= t "t5_html", :scope => "topics_list" %></li>
            <li><%= t "t6_html", :scope => "topics_list" %></li>
            <li><%= t "t7_html", :scope => "topics_list" %></li>
            <li><%= t "t8_html", :scope => "topics_list" %></li>
          </ul>
        </div>

        <!-- secondary content end -->

      </div>

      <div id="footer">

        &copy; My Website. All rights reserved. Design by <a href="http://www.nodethirtythree.com/">NodeThirtyThree</a>.

      </div>

    </div>

  </div>
</body>
</html>

test_app/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interpret Demo - Backoffice</title>
  <%= stylesheet_link_tag "private", "interpret_style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="private_content">
    <p>
      This is a demostration of a custom backoffice layout, in which you may have other sections to administrate your site. You can integrate Interpret as a one more option in the main menu:
    </p>
    <div id="backoffice_menu">
      <ul>
        <li><%= link_to "Public page", "/" %></li>
        <li><%= link_to "Other backoffice section", main_app.admin_dashboard_path %></li>
        <li><%= link_to "Translations", interpret.root_path %></li>
      </ul>
    </div>
    <div id="page">
      <%= yield %>
    </div>
  </div>
</body>
</html>

test_app/app/views/pages/archives.html.erb
<h1><%= t ".h1" %></h1>
<br/>
<p><%= t ".p1" %></p>

test_app/app/views/pages/contact.html.erb
<h1><%= t ".h1" %></h1>
<br/>
<p><%= t ".p1" %></p>

test_app/app/views/pages/index.html.erb
<div class="application">
  <div class="header">
    <h3><%= t ".title1_html" %></h3>
    <div class="date"><%= t ".date1" %></div>
  </div>
  <div class="content">
    <%= image_tag "pic1.jpg", :class => "picA floatleft" %>
    <p><%= t ".post_1_1_html" %></p>
    <p><%= t ".post_1_2_html" %></p>
  </div>
  <div class="footer">
    <ul>
      <li class="printerfriendly"><%= t "printer" %></li>
      <li class="comments"><%= t "comments" %> (18)</li>
      <li class="readmore"><%= t "read_more" %></li>
    </ul>
  </div>
</div>

<div class="post">
  <div class="header">
    <h3><%= t ".title2" %></h3>
    <div class="date"><%= t ".date2" %></div>
  </div>
  <div class="content">
    <p><%= t ".post_2_1_html" %></p>
    <p><%= t ".post_2_2_html" %></p>
  </div>
  <div class="footer">
    <ul>
      <li class="printerfriendly"><%= t "printer" %></li>
      <li class="comments"><%= t "comments" %> (18)</li>
      <li class="readmore"><%= t "read_more" %></li>
    </ul>
  </div>
</div>

<div class="post">
  <div class="header">
    <h3><%= t ".title3" %></h3>
    <div class="date"><%= t ".date3" %></div>
  </div>
  <div class="content">
    <p><%= t ".post_3_1_html" %></p>
    <p><%= t ".post_3_2_html" %></p>
  </div>
  <div class="footer">
    <ul>
      <li class="printerfriendly"><%= t "printer" %></li>
      <li class="comments"><%= t "comments" %> (18)</li>
      <li class="readmore"><%= t "read_more" %></li>
    </ul>
  </div>
</div>

test_app/app/views/pages/links.html.erb
<h1><%= t ".h1" %></h1>
<br/>
<p><%= t ".p1" %></p>

<hr>
<ul class="links">
  <li><%= t ".elem1" %></li>
  <li><%= t ".elem2" %></li>
  <li><%= t ".elem3" %></li>
</ul>

test_app/app/views/pages/resources.html.erb
<h1><%= t ".h1" %></h1>
<br/>
<p><%= t ".p1" %></p>
<p><%= t ".p2" %></p>